version: '3'

services:
  
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/marco/Desenvolvimento/Portainer/data:/data